package models

import (
	"time"
)

func UEKData(value float32) *Fund {
	unionUEK := []Union{{
		Label: "NeoSocium Union",
		IncomeAccount: []IncomeAccount{
			{Label: "ИП Лычкин А.О.", Bank: "Точка Банк"},
		},
		Team: []Team{
			{Label: "Команда УЕК"},
		},
	}}

	//Сначала расчитывается фонд с наивысшим приоритетом, затем от остатка родителя - остальные
	return (&Fund{
		Label:      "С совета на УЕК",
		Priority:   0,
		Union:      unionUEK,
		CheckChild: false,
		RuleValue:  value,
		Child: []*Fund{
			{
				Label:      "Выручка УЕК",
				Priority:   0,
				Union:      unionUEK,
				CheckChild: false,
				RuleValue:  100,
				Child: []*Fund{
					{
						Label:      "Группа Фондов Стабилизации",
						Priority:   1,
						Union:      unionUEK,
						CheckChild: true,
						RuleValue:  -1,
						Child: []*Fund{
							{
								Label:      "Фикс Команд УЕК",
								Priority:   0,
								Union:      unionUEK,
								CheckChild: false,
								RuleValue:  -1,
								Goals: []Goals{
									{
										Label:      "Оклад КК 1",
										Total:      0,
										ExpireDate: time.Now().Add(time.Hour * 24 * 14),
									},
								}},
							{
								Label:      "Фикс Капитану УЕК",
								Priority:   0,
								Union:      unionUEK,
								CheckChild: false,
								RuleValue:  -1,
								Goals: []Goals{
									{
										Label:      "Оклад Капитану УЕК",
										Total:      10000,
										ExpireDate: time.Now().Add(time.Hour * 24 * 14),
									},
								}},
							//TODO: Возврат инвестиций
							{Label: "Регулярные платежи",
								Priority:   0,
								Union:      unionUEK,
								CheckChild: false,
								RuleValue:  -1,
								Goals: []Goals{
									{
										Label:      "Регулярный платеж нулевой",
										Total:      0,
										ExpireDate: time.Now().Add(time.Hour * 24 * 14),
									},
								}},
							{Label: "Известные платежи",
								Priority:   0,
								Union:      unionUEK,
								CheckChild: false,
								RuleValue:  -1,
								Goals: []Goals{
									{
										Label:      "Известный платеж нулевой",
										Total:      0,
										ExpireDate: time.Now().Add(time.Hour * 24 * 14),
									},
								}},
						},
					},
					//Отдельное Объединение
					{
						Label:      "Чистые поступления УЕК",
						Priority:   2,
						Union:      unionUEK,
						CheckChild: false,
						RuleValue:  -1,
						Child: []*Fund{
							{
								Label:      "На УЕК",
								Priority:   0,
								Union:      unionUEK,
								CheckChild: false,
								RuleValue:  50,
								Child: []*Fund{
									{
										Label:      "Группа Фондов Устойчивости",
										Priority:   0,
										Union:      unionUEK,
										CheckChild: false,
										RuleValue:  3,
										Child: []*Fund{
											{Label: "Тушения пожаров",
												Priority:   0,
												Union:      unionUEK,
												CheckChild: false,
												RuleValue:  100,
											},
										},
									},
									{
										Label: "Группа Фондов Бонусов", Priority: 0,
										Union:      unionUEK,
										CheckChild: false,
										RuleValue:  97,
										Child: []*Fund{
											{Label: "Бонусы Командам УЕК",
												Priority:   0,
												Union:      unionUEK,
												CheckChild: false,
												RuleValue:  100,
											},
										},
									},
									{
										Label:      "Группа Фондов Достигаторов",
										Priority:   0,
										Union:      unionUEK,
										CheckChild: false,
										RuleValue:  0,
										Child: []*Fund{
											{Label: "Личностные игры",
												Priority:   0,
												Union:      unionUEK,
												CheckChild: false,
												RuleValue:  0,
											},
											{Label: "Квартальных премий по целям",
												Priority:   0,
												Union:      unionUEK,
												CheckChild: false,
												RuleValue:  0,
											},
											{Label: "Бонусы по целям Команды",
												Priority:   0,
												Union:      unionUEK,
												CheckChild: false,
												RuleValue:  0,
											},
										},
									},
									{
										Label:      "Группа Фондов Социально-психологические",
										Priority:   0,
										Union:      unionUEK,
										CheckChild: false,
										RuleValue:  0,
										Child: []*Fund{
											{
												Label:      "Высокий уровень энергии",
												Priority:   0,
												Union:      unionUEK,
												CheckChild: false,
												RuleValue:  0,
												Child: []*Fund{
													{Label: "ДМС",
														Priority:   0,
														Union:      unionUEK,
														CheckChild: false,
														RuleValue:  0, //Будет по целям
													},
													{Label: "Плюшки Спорт, Обеды, Англ",
														Priority:   0,
														Union:      unionUEK,
														CheckChild: false,
														RuleValue:  0, //Будет по целям
													},
													{Label: "Эвенты, тимбилдинг",
														Priority:   0,
														Union:      unionUEK,
														CheckChild: false,
														RuleValue:  0,
													},
												},
											},
											{
												Label: "Развитие таланта", Priority: 0,
												Union:      unionUEK,
												CheckChild: false,
												RuleValue:  0,
												Child: []*Fund{
													{Label: "Обучение и развитие",
														Priority:   0,
														Union:      unionUEK,
														CheckChild: false,
														RuleValue:  0,
													},
													{Label: "Тренинги",
														Priority:   0,
														Union:      unionUEK,
														CheckChild: false,
														RuleValue:  0,
													},
												},
											},
											{Label: "Спокойствие за разрешение внеплановой ситуации",
												Priority:   0,
												Union:      unionUEK,
												CheckChild: false,
												RuleValue:  0,
												Child: []*Fund{
													{Label: "Свободных финансов",
														Priority:   0,
														Union:      unionUEK,
														CheckChild: false,
														RuleValue:  0,
													},
												},
											},
										},
									},
								},
							},
							{
								Label:      "На Общественные фонды",
								Priority:   0,
								Union:      unionUEK,
								CheckChild: false,
								RuleValue:  20,
								Child: []*Fund{
									{
										Label:      "Группа Фондов Общеобщественных",
										Priority:   0,
										Union:      unionUEK,
										CheckChild: false,
										RuleValue:  5,
										Child: []*Fund{
											{Label: "Общественных праздников",
												Priority:   0,
												Union:      unionUEK,
												CheckChild: false,
												RuleValue:  75,
											},
											{Label: "Благотворительность",
												Priority:   0,
												Union:      unionUEK,
												CheckChild: false,
												RuleValue:  25,
											},
										},
									},
									{
										Label:      "Группа Фондов Достигаторов",
										Priority:   0,
										Union:      unionUEK,
										CheckChild: false,
										RuleValue:  95,
										Child: []*Fund{
											{Label: "Фантомных Акций",
												Priority:   0,
												Union:      unionUEK,
												CheckChild: false,
												RuleValue:  50,
											},
											{Label: "Глобальных целей",
												Priority:   0,
												Union:      unionUEK,
												CheckChild: false,
												RuleValue:  0,
											},
											{Label: "Целей ЛЛК",
												Priority:   0,
												Union:      unionUEK,
												CheckChild: false,
												RuleValue:  50,
											},
										},
									},
								},
							},
							{
								Label:      "Акционерам",
								Priority:   0,
								Union:      unionUEK,
								CheckChild: false,
								RuleValue:  30,
								Child: []*Fund{
									{Label: "Дивидендов",
										Priority:   0,
										Union:      unionUEK,
										CheckChild: false,
										RuleValue:  100,
									},
								},
							},
						},
					},
				},
			},
		},
	})
}
